### ISSUE TITLE
Database API

### ISSUE THREAD

**Issue by cprodhomme** [Scalingo/scalingo-ruby-api#28]
Hello,

I just want to know if you program to develop resources for Database API : https://developers.scalingo.com/databases/index

Thanks for your work

**Comment by ksol** [comment]
yes, it will eventually come. The differences in the authentication mechanisms make it a bit less trivial to expose it in a dev-friendly manner, which is why it was not shipped yet

**Comment by aurelien-reeves-scalingo** [comment]
Done as part of https://github.com/Scalingo/scalingo-ruby-api/pull/41

**Comment by aurelien-reeves-scalingo** [comment]
Hey @cprodhomme,

It took some time, but it is finally here. The ruby API is now capable of requesting the scalingo database API!

I hope it will fit your needs
We are already aware of a few (#44 #45) improvements to be done. Still, feel free to let us some feedback!

**Comment by cprodhomme** [comment]
Thanks for your work ! :)
