### ISSUE TITLE
Add support for the new authentication system

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/scalingo-ruby-api#4]
https://scalingo.com/articles/2018/03/29/new-auth-system.html

It prevents this gem to be used with tokens generated on the user profile. Hence it prevents this gem to be used on the osc-fr1 region.

Notify https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24506537584 when done

**Comment by Soulou** [comment]
Closed with release v2.0.0
